# Generated by Django 5.0.6 on 2024-07-03 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id_cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('cargo_emp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEnvios',
            fields=[
                ('id_estado_envio', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_envio', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosArriendo',
            fields=[
                ('id_estado_arriendo', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_arriendo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosPedido',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_pedido', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosReparacion',
            fields=[
                ('id_estado_reparacion', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_reparacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=40)),
                ('rut_prov', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id_sucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPromocion',
            fields=[
                ('id_tipo_promo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_promo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_emp', models.CharField(max_length=20)),
                ('aPaterno_emp', models.CharField(max_length=20)),
                ('aMaterno_emp', models.CharField(max_length=20)),
                ('rut_emp', models.IntegerField(verbose_name=8)),
                ('dv', models.IntegerField(verbose_name=1)),
                ('id_cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.CASCADE, to='gestion.cargos')),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='gestion.sucursales')),
            ],
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id_envio', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion_envio', models.CharField(max_length=50)),
                ('costo_envio', models.IntegerField(verbose_name=9)),
                ('fecha_envio', models.DateField()),
                ('estado_envio', models.ForeignKey(db_column='id_estado_envio', on_delete=django.db.models.deletion.CASCADE, to='gestion.estadoenvios')),
            ],
        ),
        migrations.CreateModel(
            name='InformesGestion',
            fields=[
                ('id_informe', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_informe', models.DateField()),
                ('ventas_totales', models.IntegerField(verbose_name=9)),
                ('stock_total', models.IntegerField(verbose_name=9)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='gestion.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('estado_pedido', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='gestion.estadospedido')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='gestion.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=20)),
                ('precio_unit', models.IntegerField()),
                ('impuesto', models.IntegerField()),
                ('stock_actual', models.IntegerField()),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='gestion.categoriaproducto')),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='gestion.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name=9)),
                ('fecha_entrada', models.DateField()),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMantenciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_mantencion', models.CharField(max_length=200)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name=9)),
                ('precio_unitario', models.IntegerField(verbose_name=9)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='gestion.pedidos')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Arriendos',
            fields=[
                ('id_arriendo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('forma_pago', models.CharField(max_length=20)),
                ('deposito_garantia', models.IntegerField(verbose_name=9)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('estado_arriendo', models.ForeignKey(db_column='id_estado_arriendo', on_delete=django.db.models.deletion.CASCADE, to='gestion.estadosarriendo')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Reparaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_reparacion', models.ForeignKey(db_column='id_estado_reparacion', on_delete=django.db.models.deletion.CASCADE, to='gestion.estadosreparacion')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='gestion.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id_promocion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descuento', models.IntegerField(verbose_name=9)),
                ('tipo_promocion', models.ForeignKey(db_column='id_tipo_promo', on_delete=django.db.models.deletion.CASCADE, to='gestion.tipopromocion')),
            ],
        ),
        migrations.CreateModel(
            name='TrazabilidadEnvios',
            fields=[
                ('id_trazabilidad', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, to='gestion.eventos')),
                ('id_envio', models.ForeignKey(db_column='id_envio', on_delete=django.db.models.deletion.CASCADE, to='gestion.envios')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('total_neto', models.IntegerField(verbose_name=9)),
                ('total_impuesto', models.IntegerField(verbose_name=9)),
                ('total_final', models.IntegerField(verbose_name=9)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='gestion.pedidos')),
            ],
        ),
        migrations.AddField(
            model_name='envios',
            name='id_venta',
            field=models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='gestion.ventas'),
        ),
    ]
