# Generated by Django 5.0.6 on 2024-06-27 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_categoria_productos_categoriaproductos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='categoria',
            new_name='id_categoria',
        ),
    ]
