# Generated by Django 5.0.6 on 2024-07-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_proveedor_cliente_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut_prov',
            field=models.CharField(max_length=20),
        ),
    ]
