# Generated by Django 5.0.6 on 2024-07-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_proveedor_email_alter_proveedor_rut_prov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pagina_web',
            field=models.URLField(),
        ),
    ]
