# Generated by Django 5.0.6 on 2024-06-29 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rename_categoria_productos_id_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=20)),
                ('precio_unit', models.IntegerField(verbose_name=9)),
                ('impuesto', models.IntegerField(verbose_name=9)),
                ('stock_actual', models.IntegerField(verbose_name=9)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='gestion.categoriaproductos')),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='gestion.proveedores')),
            ],
        ),
        migrations.AlterField(
            model_name='arriendos',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='gestion.producto'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='gestion.producto'),
        ),
        migrations.AlterField(
            model_name='historialmantenciones',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='gestion.producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='gestion.producto'),
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
