# Generated by Django 5.0.6 on 2024-06-30 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_producto_alter_arriendos_id_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='cargo_emp',
            new_name='id_cargo',
        ),
    ]
