# Generated by Django 5.0.6 on 2024-07-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_cliente_user_id_alter_proveedor_pagina_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='id_empleado',
        ),
    ]
