# Generated by Django 5.0.6 on 2024-07-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_pedidos_id_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='id_cliente',
            field=models.IntegerField(),
        ),
    ]
