# Generated by Django 5.0.6 on 2024-06-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_empleado_alter_informesgestion_id_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rut_emp',
            field=models.IntegerField(max_length=8),
        ),
    ]
