# Generated by Django 5.0.6 on 2024-06-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_empleado_rut_emp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaProductos',
            new_name='CategoriaProducto',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dv',
            field=models.IntegerField(verbose_name=1),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rut_emp',
            field=models.IntegerField(verbose_name=8),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
