# Generated by Django 5.0.6 on 2024-07-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='direccion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dvRut',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='numRut',
            field=models.IntegerField(null=True, verbose_name=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(null=True, verbose_name=9),
        ),
    ]
