# Generated by Django 5.0.6 on 2024-07-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_direccion_alter_user_dvrut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo', models.IntegerField()),
                ('nombre_tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='numRut',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_tipo',
            field=models.ForeignKey(db_column='id_tipo', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.tipo_user'),
            preserve_default=False,
        ),
    ]
