# Generated by Django 5.0.6 on 2024-07-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_id_tipo_user_id_tipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_User',
            new_name='TipoUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_tipe',
        ),
    ]
