# Generated by Django 5.0.6 on 2024-07-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_tipo_user_tipouser_remove_user_id_tipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_tipo',
            field=models.IntegerField(default=1),
        ),
    ]
